### ISSUE TITLE
Run Demo error

### ISSUE THREAD

**Issue by kqw94** [huochaitiantang/pytorch-deep-image-matting#20]
Hi, I meet this error when I try to run the code/demo.py, anyone solve it?
> Traceback (most recent call last):
  File "core/demo.py", line 42, in <module>
    ckpt = torch.load(args.resume)
  File "/home/mmdb-gp8/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/home/mmdb-gp8/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0x94 in position 1: ordinal not in range(128)

BTW, the model Stage1-SAD=57.1 can not be access ☹️

**Comment by kqw94** [comment]
Swith python2.7 solve this problem
