### ISSUE TITLE
运行demo.py收到了一个报错

### ISSUE THREAD

**Issue by exition** [huochaitiantang/pytorch-deep-image-matting#43]
Load Error:'utf-8' codec can't decode byte 0xda in position 5: invalid continuation byte
Try Load Again...
Traceback (most recent call last):
  File ".\core\demo.py", line 17, in my_torch_load
    ckpt = torch.load(fname)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 765, in _legacy_load
    result = unpickler.load()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 5: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\core\demo.py", line 66, in <module>
    ckpt = my_torch_load(args.resume)
  File ".\core\demo.py", line 30, in my_torch_load
    ckpt = torch.load(args.resume, pickle_module=c)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
TypeError: c_load() got an unexpected keyword argument 'encoding'

我的 python版本是3.7.4

**Comment by hmate9** [comment]
In `demo.py` change `ckpt = torch.load(args.resume, pickle_module=c)` to `ckpt = torch.load(args.resume, encoding='latin1')`
